[package]
name = "sn_basecamp"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.12.0"
cairo_execute = "2.12.0"


[dev-dependencies]
snforge_std = "0.48.0"
assert_macros = "2.12.0"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"

# ...
[cairo]
enable-gas = false


[[target.executable]]
name = "hello_world_main"
function = "hello_world::hello_world::main"
